# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='custumuser',
            name='name',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
