# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161101_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='custumuser',
            name='hsnGroup',
            field=models.BooleanField(default=False),
        ),
    ]
