# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_custumuser_hsngroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custumuser',
            old_name='hsnGroup',
            new_name='hasGroup',
        ),
    ]
