# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161103_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='custumuser',
            name='profileImage',
            field=models.ImageField(default='profiles/default.jpg', upload_to='profiles/'),
        ),
    ]
