# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20161101_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('classNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ManyToManyField(to='accounts.CustumUser')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_room.Student'),
        ),
    ]
