# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_room', '0002_auto_20161103_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='classNumber',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='class',
            name='grade',
        ),
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(default='test', max_length=20),
        ),
    ]
