# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_room', '0006_auto_20161104_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='post',
            field=models.ManyToManyField(null=True, related_name='post_set', to='class_room.Post'),
        ),
    ]
