# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161103_2009'),
        ('class_room', '0007_auto_20161104_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_set', to='accounts.CustumUser')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='commenter',
            field=models.ManyToManyField(related_name='commenter_set', to='accounts.CustumUser'),
        ),
    ]
