# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161101_1939'),
        ('class_room', '0003_auto_20161103_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_set', to='accounts.CustumUser'),
        ),
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(null=True, related_name='student_set', to='accounts.CustumUser'),
        ),
    ]
