# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161103_2009'),
        ('class_room', '0004_auto_20161103_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='requestUser',
            field=models.ManyToManyField(null=True, related_name='request_list_set', to='accounts.CustumUser'),
        ),
    ]
