# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_room', '0008_auto_20161104_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commenter',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.ManyToManyField(related_name='commenter_set', to='class_room.Comment'),
        ),
    ]
