# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_room', '0009_auto_20161104_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_set', to='accounts.CustumUser'),
        ),
    ]
